### ISSUE TITLE
[bug]cmdb 资产更新时会丢失主机名正确性

### ISSUE THREAD

**Issue by jefffffffffffffffff** [opendevops-cn/codo-cmdb#13]
版本:0.3
部署方式:虚拟机跑docker
环境描述:
以项目为单位,孵化的各个环境的虚拟机,如 python-test-web项目,如要孵化测试环境的虚拟机,则主机名为python-test-web.xxxxxxx.test.xxxx,每个虚拟机的id都是不同的.

问题现象:
10.200.3.200 是第一次添加的主机,添加完成点击 资产更新 ,没有问题,此时主机名已经被截断,如图;
![image](https://user-images.githubusercontent.com/12181410/61025211-8f158780-a3e2-11e9-9914-ab7cda90a4bf.png)

10.200.8.6 是第二次添加的主机,绝对不同于10.200.3.200的 资产信息,点击资产更新报错,如图:
![image](https://user-images.githubusercontent.com/12181410/61025416-3d213180-a3e3-11e9-8ada-f4489d2fe6cc.png)

此时,因第一次添加的主机在资产更新时 主机名被截断,导致添加第二台主机(相同前缀的主机名,后缀每个主机都不一样)报主键重复.

请修复此BUG.

**Comment by yanghongfei** [comment]
主机名测试了 点的话是会被ansbile直接过滤掉， - _ 这种都可以
