### ISSUE TITLE
[BUG] 编辑主机保存时报22端口必须输入

### ISSUE THREAD

**Issue by jefffffffffffffffff** [opendevops-cn/codo-cmdb#16]
版本:0.3
部署方式:虚拟机运行容器
问题现象:
编辑主机保存时报22端口必须输入,都能编辑,说明添加主机时22端口是校验通过的.如图:
![image](https://user-images.githubusercontent.com/12181410/61026659-7c04b680-a3e6-11e9-8954-f8226cbd2c8d.png)
请修复此BUG

**Comment by yanghongfei** [comment]
这个地方是属于iview的常见问题，很多人遇到，编辑都会用到，除非不填上，或者不进行规则检测
